runtime: python311
service: vertex-ai-rag

env_variables:
  GOOGLE_CLOUD_PROJECT: "dotd-development-division"
  GEMINI_MODEL: "gemini-2.5-flash"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 0
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

entrypoint: gunicorn -b :$PORT -w 1 --threads 8 --timeout 0 app:app 