steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vertex-ai-rag:$COMMIT_SHA', '.']
  
  # イメージをContainer Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vertex-ai-rag:$COMMIT_SHA']
  
  # 最新タグも付与
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/vertex-ai-rag:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/vertex-ai-rag:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vertex-ai-rag:latest']

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vertex-ai-rag'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vertex-ai-rag:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '3600'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'

images:
  - 'gcr.io/$PROJECT_ID/vertex-ai-rag:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vertex-ai-rag:latest' 